version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: edu-db
    environment:
      POSTGRES_DB: edu_sentinel_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: edu-sentinel-app
    ports:
      - "8085:8085"
    environment:
      DBMS_CONNECTION: jdbc:postgresql://db:5432/edu_sentinel_db
      DBMS_USERNAME: postgres
      DBMS_PASSWORD: postgres
    depends_on:
      - db

volumes:
  postgres_data: